### ISSUE TITLE
Cannot use ${PRODUCT_NAME} because it does not work on Intel-based macs.

### ISSUE THREAD

**Issue by edude03** [ivanvc/mongodb-prefpane#1]
That's the error I got after compiling and installing this app. Please let me know if I missed something. Thanks

**Comment by ivanvc** [comment]
Am not able to reproduce this on an Intel based mac. Is this happening after you compiled it? Or you are using the precompiled version? Also, can you try with the new version (0.0.2)?

**Comment by dbourguignon** [comment]
same problem here, using compilation from source, with the latest sources

The pre-compiled version does not display the same behaviour but the ON/OFF button does not work (stay on OFF)

In console I have :
System Preferences[72157:903] [NSPrefPaneBundle instantiatePrefPaneObject](/Users/bourgui/Library/PreferencePanes/mongodb.prefpane): principalClass is nil.

**Comment by ivanvc** [comment]
Interesting.. Can you let me know which Mac OS and Xcode versions you have?

**Comment by dbourguignon** [comment]
Sure, 

Using Mac OS 10.6.7 and XCode 4.0.1

**Comment by ivanvc** [comment]
Ooooh, now I see what's the problem... It's because of the project name. Seems like OS X is trying to open it as a preference pane.

So, what you need to do (if you have already cloned the repo). Go in the Terminal to the project root, there run `open mongodb.prefpane.xcodeproj`, compile the project (cmd + B). Then, point a Finder window to `~/Library/Developer/Xcode/DerivedData/`. There should be a folder called: `mongodb.prefpane-{some random characters}`. Once there, go to `Build/Products/{Debug,Release}`. And finally, there's the file. The output directory was changed in Xcode 4, and is no longer in the project root's build folder, so this is a little tricky.

I'm going to change de project name to avoid this confusion. Let me know if this fixes the problem, I know it should.

**Comment by ivanvc** [comment]
Just a ping, because GitHub told me that renaming the project won't update any link...

**Comment by ivanvc** [comment]
Also, there's the latest build now in the downloads section.

**Comment by dbourguignon** [comment]
OK, great it now works

**Comment by ivanvc** [comment]
I'm improving the project to keep cleaner integration, so come back soon. :)

**Comment by edude03** [comment]
Thanks, the issue was fixed.
